- hosts: wordpress
  remote_user: birth
  become: yes
  tasks:
    - name: "Executa o container MySQL"
      docker_container:
        name: banco2
        image: projetodeblocobanco:1.1
        env:
          MYSQL_ROOT_PASSWORD: senha123
          MYSQL_DATABASE: wordpress
          MYSQL_USER: wordpress
          MYSQL_PASSWORD: senha123
 
    - name: "Executa o container WordPress"
      docker_container:
        name: wordpress2
        image: projetodeblocowp:1.1 
        env:
          WORDPRESS_DB_HOST: banco2:3306
          WORDPRESS_DB_USER: wordpress
          WORDPRESS_DB_PASSWORD: senha123
        links:
          - "banco2:projetodeblocobanco"
        ports:
          - "80:80"
